name: "build-push-ecr"
on: [push]

jobs:
  BUILD_PUSH:
    name: Build Docker Image And Push To ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the tagged docker image to Amazon ECR
        id: containerImage
        env:
          ECR_REGISTRY: ${{ secrets.ECR_URL }}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          ACCOUNT_PASS: ${{ secrets.PASSWORD}}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t python-app .
          docker tag python-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker login --username AWS -p $ACCOUNT_PASS $ECR_REGISTRY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
